Landing page
gogurlbaby/portfolio pull request #1
Opened 2023-09-09 09:50 UTC by gogurlbaby

completed navbar and hero section

2023-09-09 11:33 UTC, barakadanny requested changes
## Required Changes ♻️

Hi @gogurlbaby.

Good job so far!
There are some issues that you still need to work on to go to the next task but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Professional UI
✔️ Correct Gitflow

## Required 
- [x] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@barakadanny] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-09-09 11:33 UTC, barakadanny commented on styles/hero.css
> +    /* width: 50%; */
- [ ] If you have defined CSS classes in your stylesheet but haven't applied any styles to them, it's a good practice to remove those class selectors entirely. This helps in reducing the file size and keeps your CSS codebase tidy.

2023-09-09 11:33 UTC, barakadanny commented on styles/hero.css
- [ OPTIONAL ] Consider using CSS variables (custom properties) to define colors, font families, and other common values. This can make it easier to update the styling of your website globally.

sample:

``` css
/* Define CSS variables for colors */
:root {
    --primary-color: #21243D;
    --button-background: #FF6464;
    --button-border: #FF6464;
    --button-text: #FFF;
}

/* Rest of your CSS styles */
.title {
    color: var(--primary-color);
    /* ...other styles... */
}

.hero-btn {
    border-radius: 2px;
    background: var(--button-background);
    border: 1px solid var(--button-border);
    color: var(--button-text);
    /* ...other styles... */
}
```

**you can read more about that [here](https://www.freecodecamp.org/news/what-are-css-variables-and-how-to-use-them/)**

2023-09-09 11:33 UTC, barakadanny commented on index.html
- [ ] Consider adding a `<header>` element to enclose the navigation bars. This will provide a more semantic structure and make it easier for screen readers and search engines to understand the content.
- [ ] In the script tag at the bottom of the body, you have an extra `</script>` tag. Remove the extra `</script>` tag.
- [ ] Consider moving your JavaScript code to an external file and then linking to it using a `<script>` tag with a src attribute. This can help keep your HTML cleaner and make your code more maintainable.
- [ ] I recommend consolidating the navigation structure into a single <nav> element for both mobile and desktop versions of the website. This will simplify the code and make it easier to maintain in the long run.

2023-09-11 23:17 UTC, gogurlbaby commented on index.html
I have made the necessary changes but having slight issues with the navbar after using same structure for both mobile and desktop. The menu items for desktop fails to show. I need help with that. It seems I'm not implementing something well. 

I will be adding the other sections soon and push. I don't want to waste too much time on correcting the navbar now. Will be looking forward to your review soon.

2023-09-15 15:26 UTC, gogurlbaby commented on index.html
I have completed the recent posts, featured works and footer sections. I created a JSON file for the recent posts to be read from there. I used JavaScript to implement that but it is not working. I will need help with how to go about that correctly.

2023-09-23 12:37 UTC, gogurlbaby commented
I just pushed the new changes requested. The menu-button to hide when the overlay shows fails. Since its more of JavaScript I decided to wait when we start with it.

2024-02-21 16:58 UTC, merged